name: Deploy pkgdown site

on:
  push:
    branches:
      - master  # or the branch you usually push to

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'usethis', 'rcmdcheck', 'rversions', 'urlchecker'))"
          Rscript -e "remotes::install_cran('pkgdown')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Build pkgdown site
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
